DROP TABLE *;

CREATE TABLE USERS (
id INT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(30),
last_name VARCHAR(30),
user_name VARCHAR(30) UNIQUE,
email VARCHAR(30) UNIQUE,
gender VARCHAR(10),
about VARCHAR(200),
created_at DATE,
PRIMARY KEY (id)
);

CREATE TABLE `GROUPS`(
id INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30),
`about` VARCHAR(30),
OWNER INT,
created_at DATE,
PRIMARY KEY (id),
FOREIGN KEY (OWNER) REFERENCES USERS(id)
);

CREATE TABLE USERS_CHATS(
id INT AUTO_INCREMENT,
from_user INT,
to_user INT,
msg VARCHAR(255),
created_at DATE,
PRIMARY KEY (id),
FOREIGN KEY (from_user) REFERENCES USERS(id),
FOREIGN KEY (to_user) REFERENCES USERS(id)
);

CREATE TABLE GROUPS_CHATS(
id INT AUTO_INCREMENT,
from_user INT,
msg VARCHAR(255),
created_at DATE,
PRIMARY KEY (id)
);

CREATE TABLE GROUPS_SUBSCRIBERS(
id INT AUTO_INCREMENT,
group_id INT,
user_id INT,
created_at DATE,
PRIMARY KEY (id),
FOREIGN KEY (group_id) REFERENCES `GROUPS`(id),
FOREIGN KEY (user_id) REFERENCES USERS(id)
);